name: Jira Sync

on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Jira issue
        uses: atlassian/gajira-create@v3
        with:
          jira-base-url: "https://attarmau111.atlassian.net"
          jira-user-email: "attarmau111@gmail.com"
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
          project: "KAN"
          issue-summary: "Auto-sync commit to Jira"
          issue-description: "Commit synced from GitHub"
